### ISSUE TITLE
[Hacktoberfest]: Add Content about the Rockstar Programming Language to Step 11

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#109] opened 2020-10-03 11:00 UTC
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:
Around line 175 of the Readme, is the **And Then What** Section, add in the **Coding with Rockstar** details

📋 Step by Step

* 🙋 Claim this issue by commenting on it.
* Create a New Branch [How to branch, Commit, Pull, Merge - start at step2](https://guides.github.com/activities/hello-world/)
* Make your change - I use [Github Desktop](https://desktop.github.com/) and [Visual Studio Code](https://code.visualstudio.com/) so I don't have to do anything via the command-line, but if you like the command-line git on with it ;-)

The change I suggest is go to the **And Then What** Section, starts around line 175. Add an entry after the last one in the section that reads:

`| [Code with Rockstar](https://codewithrockstar.com/) | Dylan Beattie | 11 | Rockstar is a computer programming language designed for creating programs that are also heavy metal power ballads - it's not for the faint of heart |`

* Commit it [Make it a good one](https://dev.to/chrissiemhrk/git-commit-message-5e21)
* Make a Pull Request [Tell us what you did](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)
* We'll review it and merge it in
* Add yourself as a Contributor to the bottom of the Readme.md using the same formatting as the others in the list

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by utsav00** [comment] 2020-10-03 11:34
Hey, the description is great! I think I understood most of the things.
This won't be my first contribution but I'm still a beginner. May I work on this?

**Comment by codess-aus** [comment] 2020-10-03 11:38
Sure, have at it

**Comment by utsav00** [comment] 2020-10-03 12:10
I committed to the local branch and now when I'm trying to push to ` issue-109-_Hacktoberfest_Add_Content_about_the_Rockstar_Programming_Language_to_Step_11`, it gives me `Permission Denied` error.

**Comment by codess-aus** [comment] 2020-10-03 12:32
Does it give you an option to do something else? Because you don't want to push, you want to create a Pull request. i.e a Request to Pull your changes from your local branch to my repo.

* Are you making your changes in command-line or in github desktop or directly from visual studio code, or something else?
* Is it asking you to compare across branches or make a Pull Request to merge into the main repository?

Try whatever it suggests you do next.

Else, here is another instruction I made, specifically with screenshots from this repo: https://github.com/msandfor/10-Easy-Steps/blob/master/docs/github-desktop-tutorial.md

**Comment by utsav00** [comment] 2020-10-03 14:53
Thank you for your help! I figured that I had not forked the repository and the error was caused by that.

**Comment by utsav00** [comment] 2020-10-03 14:55
Also, really sorry about two PRs, did not realize that the first PR was to the msandfor:sub-branch, so created another PR to the msandfor:master. To top it off, I learned today that I cannot delete a PR. Again really sorry about the mess.

**Closed as completed** 2020-10-03 15:15 UTC
Labels: documentation :memo:, help wanted :hand:, good first issue, hacktoberfest :children_crossing:, beginner, beginner-friendly, first-contribution, up-for-grabs

**Comment by codess-aus** [comment] 2020-10-03 15:26
@utsav00 Don't worry about it - this is the point of hacktoberfest - and this repository. For you to practice and have a chance to feel confident in Github. Now... I have created another tutorial, showing how to edit in the browser - not sure if you did that. 
See how you like this one and try another issue:
https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md

**Comment by utsav00** [comment] 2020-10-03 15:48
No, I did it with command line, I'll try it with the in-browser tools too!
Thank you for all the help! :smile:

**Comment by codess-aus** [comment] 2020-10-03 15:54
Oh well, I get lost in command-line so I don't blame you for getting mixed up in there :-D
